project_id = "jdyekwizsviuyklsrsky"

[functions.search-subtitles]
verify_jwt = false

[functions.download-subtitle]
verify_jwt = false

[functions.translate-subtitles]
verify_jwt = false

[functions.download-youtube-video]
verify_jwt = false

[functions.cut-video-segment]
verify_jwt = false

[functions.identify-song]
verify_jwt = false

[functions.analyze-description]
verify_jwt = false

[functions.adjust-subtitle-timing]
verify_jwt = false

[functions.cleanup-expired-files]
verify_jwt = false